FV3Dataset:
    file_prefixes:
        - bfg_
        - sfg_

    path_out        : "../zstores/replay-1deg"
    forecast_hours  : [0, 3]

    chunks_in:
        # estimated 37MB per chunk (the full 3D field)
        time        : 1
        pfull       : 127
        grid_yt     : 192
        grid_xt     : 384

    chunks_out:
        # estimated 2MB per chunk
        time        : 1
        pfull       : 127
        grid_yt     : 64
        grid_xt     : 64

    coords:
        - phalf
        - pfull
        - grid_xt
        - grid_yt
        - ak
        - bk

    data_vars:
        # 3D atmospheric vars
        - tmp
        - ugrd
        - vgrd
        - dpres
        - spfh
        - o3mr
        # 3D land vars
        - soilt1
        - soilt2
        - soilt3
        - soilt4
        - soill1
        - soill2
        - soill3
        - soill4
        - soilw1
        - soilw2
        - soilw3
        - soilw4
        # 2D vars
        - snod
        - prateb_ave
        - pressfc
        - weasd
        - f10m
        - sfcr
        # Surface forcing vars
        - land
        - vtype
        - sotyp
        - veg
        - icec
        - tmpsfc
        # Ease comparison
        - tmp2m
        - ugrd2m
        - vgrd2m
